"""empty message

Revision ID: 00386f8e39ad
Revises: 106ea551ca18
Create Date: 2020-06-03 21:24:51.243085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00386f8e39ad'
down_revision = '106ea551ca18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('language', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'language')
    # ### end Alembic commands ###
