"""followers

Revision ID: 106ea551ca18
Revises: 131f1368042a
Create Date: 2020-06-03 11:25:00.245700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '106ea551ca18'
down_revision = '131f1368042a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
